package com.xworkz.springexamples.boot;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.xworkz.springexamples.bean.Animals;
import com.xworkz.springexamples.bean.Apple;
import com.xworkz.springexamples.bean.Area;
import com.xworkz.springexamples.bean.Area1;
import com.xworkz.springexamples.bean.Area2;
import com.xworkz.springexamples.bean.Area3;
import com.xworkz.springexamples.bean.Bag;
import com.xworkz.springexamples.bean.Bathroom;
import com.xworkz.springexamples.bean.Bear;
import com.xworkz.springexamples.bean.Bed;
import com.xworkz.springexamples.bean.Belt;
import com.xworkz.springexamples.bean.Bike;
import com.xworkz.springexamples.bean.Book;
import com.xworkz.springexamples.bean.Bottel;
import com.xworkz.springexamples.bean.Bus;
import com.xworkz.springexamples.bean.Cement;
import com.xworkz.springexamples.bean.Chair;
import com.xworkz.springexamples.bean.Cloth;
import com.xworkz.springexamples.bean.Colors;
import com.xworkz.springexamples.bean.Cycle;
import com.xworkz.springexamples.bean.Dog;
import com.xworkz.springexamples.bean.Door;
import com.xworkz.springexamples.bean.Email;
import com.xworkz.springexamples.bean.Fan;
import com.xworkz.springexamples.bean.Fridge;
import com.xworkz.springexamples.bean.Fruit;
import com.xworkz.springexamples.bean.Hair;
import com.xworkz.springexamples.bean.Hero;
import com.xworkz.springexamples.bean.Hospital;
import com.xworkz.springexamples.bean.Hotel;
import com.xworkz.springexamples.bean.Iron;
import com.xworkz.springexamples.bean.Laptop;
import com.xworkz.springexamples.bean.Lolipop;
import com.xworkz.springexamples.bean.Mall;
import com.xworkz.springexamples.bean.Man;
import com.xworkz.springexamples.bean.Metro;
import com.xworkz.springexamples.bean.Mobile;
import com.xworkz.springexamples.bean.Numbers;
import com.xworkz.springexamples.bean.Pen;
import com.xworkz.springexamples.bean.Pencil;
import com.xworkz.springexamples.bean.Petrol;
import com.xworkz.springexamples.bean.Pg;
import com.xworkz.springexamples.bean.Pillow;
import com.xworkz.springexamples.bean.Plane;
import com.xworkz.springexamples.bean.Price;
import com.xworkz.springexamples.bean.Pump;
import com.xworkz.springexamples.bean.Rubber;
import com.xworkz.springexamples.bean.Sallon;
import com.xworkz.springexamples.bean.Shirt;
import com.xworkz.springexamples.bean.Slipper;
import com.xworkz.springexamples.bean.Table;
import com.xworkz.springexamples.bean.Temple;
import com.xworkz.springexamples.bean.Tennis;
import com.xworkz.springexamples.bean.Train;
import com.xworkz.springexamples.bean.Tree;
import com.xworkz.springexamples.bean.Vegitable;
import com.xworkz.springexamples.bean.Vibrator;
import com.xworkz.springexamples.bean.Window;
import com.xworkz.springexamples.bean.Wire;
import com.xworkz.springexamples.configuration.SpringConfig;

public class SpringElite {

	public static void main(String[] args) {

		ApplicationContext context=new AnnotationConfigApplicationContext(SpringConfig.class);
		System.out.println("HashCode od Apple:" + context.getBean(Apple.class).hashCode());
		System.out.println("HashCode od Bag:" + context.getBean(Bag.class).hashCode());
		System.out.println("HashCode od Hotel:" + context.getBean(Hotel.class).hashCode());
		System.out.println("HashCode od Hospital:" + context.getBean(Hospital.class).hashCode());
		System.out.println("HashCode od Temple:" + context.getBean(Temple.class).hashCode());
		System.out.println("HashCode od Bathroom:" + context.getBean(Bathroom.class).hashCode());
		System.out.println("HashCode od Email:" + context.getBean(Email.class).hashCode());
		System.out.println("HashCode od Cycle:" + context.getBean(Cycle.class).hashCode());
		System.out.println("HashCode od Train:" + context.getBean(Train.class).hashCode());
		System.out.println("HashCode od Slipper:" + context.getBean("Slipper",String.class).hashCode());
		System.out.println("HashCode od Area:" + context.getBean("Area",String.class).hashCode());
		System.out.println("HashCode od Area1:" + context.getBean("Area1",String.class).hashCode());
		System.out.println("HashCode od Area2:" + context.getBean("Area2",String.class).hashCode());
		System.out.println("HashCode od Area3:" + context.getBean("Area3",String.class).hashCode());
		System.out.println("HashCode od Area4:" + context.getBean("Area4",String.class).hashCode());
		System.out.println("HashCode od Area5:" + context.getBean("Area5",String.class).hashCode());
		System.out.println("HashCode od Area6:" + context.getBean("Area6",String.class).hashCode());
		System.out.println("HashCode od Area7:" + context.getBean("Area7",String.class).hashCode());
		System.out.println("HashCode od Area8:" + context.getBean("Area8",String.class).hashCode());
		System.out.println("HashCode od Area9:" + context.getBean("Area9",String.class).hashCode());
		System.out.println("HashCode od Area10:" + context.getBean("Area10",String.class).hashCode());
		System.out.println("HashCode of Bear:" + context.getBean(Bear.class).hashCode());
		System.out.println("HashCode of Bed:" + context.getBean(Bed.class).hashCode());
		System.out.println("HashCode of Belt:" + context.getBean(Belt.class).hashCode());
		System.out.println("HashCode of Bike:" + context.getBean(Bike.class).hashCode());
		System.out.println("HashCode of Book:" + context.getBean(Book.class).hashCode());
		System.out.println("HashCode of Bottle:" + context.getBean(Bottel.class).hashCode());
		System.out.println("HashCode of Bus:" + context.getBean(Bus.class).hashCode());
		System.out.println("HashCode of Cement:" + context.getBean(Cement.class).hashCode());
		System.out.println("HashCode of Chair:" + context.getBean(Chair.class).hashCode());
		System.out.println("HashCode of Cloth:" + context.getBean(Cloth.class).hashCode());
		System.out.println("HashCode of Dog:" + context.getBean(Dog.class).hashCode());
		System.out.println("HashCode of Door:" + context.getBean(Door.class).hashCode());
		System.out.println("HashCode of Bullet:" + context.getBean(com.xworkz.springexamples.bean.Bullet.class).hashCode());
		System.out.println("HashCode of Fan:" + context.getBean(Fan.class).hashCode());
		System.out.println("HashCode of Fridge:" + context.getBean(Fridge.class).hashCode());
		System.out.println("HashCode of Fruit:" + context.getBean(Fruit.class).hashCode());
		System.out.println("HashCode of Hair:" + context.getBean(Hair.class).hashCode());
		System.out.println("HashCode of Hero:" + context.getBean(Hero.class).hashCode());
		System.out.println("HashCode of Iron:" + context.getBean(Iron.class).hashCode());
		System.out.println("HashCode of Laptop:" + context.getBean(Laptop.class).hashCode());
		System.out.println("HashCode of Lolipop:" + context.getBean(Lolipop.class).hashCode());
		System.out.println("HashCode of Mall:" + context.getBean(Mall.class).hashCode());
		System.out.println("HashCode of Man:" + context.getBean(Man.class).hashCode());
		System.out.println("HashCode of Mobile:" + context.getBean(Mobile.class).hashCode());
		System.out.println("HashCode of Pen:" + context.getBean(Pen.class).hashCode());
		System.out.println("HashCode of Pencil:" + context.getBean(Pencil.class).hashCode());
		System.out.println("HashCode of Petrol:" + context.getBean(Petrol.class).hashCode());
		System.out.println("HashCode of Pg:" + context.getBean(Pg.class).hashCode());
		System.out.println("HashCode of Pillow:" + context.getBean(Pillow.class).hashCode());
		System.out.println("HashCode of Plane:" + context.getBean(Plane.class).hashCode());
		System.out.println("HashCode of Price:" + context.getBean(Price.class).hashCode());
		System.out.println("HashCode of Pump:" + context.getBean(Pump.class).hashCode());
		System.out.println("HashCode of Rubber:" + context.getBean(Rubber.class).hashCode());
		System.out.println("HashCode of Sallon:" + context.getBean(Sallon.class).hashCode());
		System.out.println("HashCode of Shirt:" + context.getBean(Shirt.class).hashCode());
		System.out.println("HashCode of Slipper:" + context.getBean(Slipper.class).hashCode());
		System.out.println("HashCode of Table:" + context.getBean(Table.class).hashCode());
		System.out.println("HashCode of Tennis:" + context.getBean(Tennis.class).hashCode());
		System.out.println("HashCode of Tree:" + context.getBean(Tree.class).hashCode());
		System.out.println("HashCode of Vegitable:" + context.getBean(Vegitable.class).hashCode());
		System.out.println("HashCode of Vibrator:" + context.getBean(Vibrator.class).hashCode());
		System.out.println("HashCode of Window:" + context.getBean(Window.class).hashCode());
		System.out.println("HashCode of Wire:" + context.getBean(Wire.class).hashCode());
		System.out.println("HashCode of bike1:" + context.getBean("bike1",String.class).hashCode());
		System.out.println("HashCode of bike2:" + context.getBean("bike2",String.class).hashCode());
		System.out.println("HashCode of bike3:" + context.getBean("bike3",String.class).hashCode());
		System.out.println("HashCode of bike4:" + context.getBean("bike4",String.class).hashCode());
		System.out.println("HashCode of bike5:" + context.getBean("bike5",String.class).hashCode());
		System.out.println("HashCode of bike6:" + context.getBean("bike6",String.class).hashCode());
		System.out.println("HashCode of bike7:" + context.getBean("bike7",String.class).hashCode());
		System.out.println("HashCode of bike8:" + context.getBean("bike8",String.class).hashCode());
		System.out.println("HashCode of bike9:" + context.getBean("bike9",String.class).hashCode());
		System.out.println("HashCode of bike10:" + context.getBean("bike10",String.class).hashCode());
		System.out.println("HashCode of bike11:" + context.getBean("bike11",String.class).hashCode());
		System.out.println("HashCode of bike12:" + context.getBean("bike12",String.class).hashCode());
		System.out.println("HashCode of bike13:" + context.getBean("bike13",String.class).hashCode());
		System.out.println("HashCode of bike14:" + context.getBean("bike14",String.class).hashCode());
		System.out.println("HashCode of bike15:" + context.getBean("bike15",String.class).hashCode());
		System.out.println("HashCode of bike16:" + context.getBean("bike16",String.class).hashCode());
		System.out.println("HashCode of bike17:" + context.getBean("bike17",String.class).hashCode());
		System.out.println("HashCode of bike18:" + context.getBean("bike18",String.class).hashCode());
		System.out.println("HashCode of bike19:" + context.getBean("bike19",String.class).hashCode());
		System.out.println("HashCode of bike20:" + context.getBean("bike20",String.class).hashCode());
		System.out.println("HashCode of bike21:" + context.getBean("bike21",String.class).hashCode());
		System.out.println("HashCode of bike22:" + context.getBean("bike22",String.class).hashCode());
		System.out.println("HashCode of bike23:" + context.getBean("bike23",String.class).hashCode());
		System.out.println("HashCode of bike24:" + context.getBean("bike24",String.class).hashCode());
		System.out.println("HashCode of bike25:" + context.getBean("bike25",String.class).hashCode());
		System.out.println("HashCode of bike26:" + context.getBean("bike26",String.class).hashCode());
		System.out.println("HashCode of bike27:" + context.getBean("bike27",String.class).hashCode());
		System.out.println("HashCode of bike28:" + context.getBean("bike28",String.class).hashCode());
		System.out.println("HashCode of bike29:" + context.getBean("bike29",String.class).hashCode());
		System.out.println("HashCode of bike30:" + context.getBean("bike30",String.class).hashCode());
		System.out.println("HashCode of bike31:" + context.getBean("bike31",String.class).hashCode());
		System.out.println("HashCode of bike32:" + context.getBean("bike32",String.class).hashCode());
		System.out.println("HashCode of bike33:" + context.getBean("bike33",String.class).hashCode());
		System.out.println("HashCode of bike34:" + context.getBean("bike34",String.class).hashCode());
		System.out.println("HashCode of bike35:" + context.getBean("bike35",String.class).hashCode());
		System.out.println("HashCode of bike36:" + context.getBean("bike36",String.class).hashCode());
		System.out.println("HashCode of bike37:" + context.getBean("bike37",String.class).hashCode());
		System.out.println("HashCode of bike38:" + context.getBean("bike38",String.class).hashCode());
		System.out.println("HashCode of bike39:" + context.getBean("bike39",String.class).hashCode());
		System.out.println("HashCode of bike40:" + context.getBean("bike40",String.class).hashCode());
		System.out.println("HashCode of bike41:" + context.getBean("bike41",String.class).hashCode());
		System.out.println("HashCode of bike42:" + context.getBean("bike42",String.class).hashCode());
		System.out.println("HashCode of bike43:" + context.getBean("bike43",String.class).hashCode());
		System.out.println("HashCode of bike44:" + context.getBean("bike44",String.class).hashCode());
		System.out.println("HashCode of bike45:" + context.getBean("bike45",String.class).hashCode());
		System.out.println("HashCode of bike46:" + context.getBean("bike46",String.class).hashCode());
		System.out.println("HashCode of bike47:" + context.getBean("bike47",String.class).hashCode());
		System.out.println("HashCode of bike48:" + context.getBean("bike48",String.class).hashCode());
		System.out.println("HashCode of bike49:" + context.getBean("bike49",String.class).hashCode());
		System.out.println("HashCode of bike50:" + context.getBean("bike50",String.class).hashCode());
		
		Metro metro= context.getBean(Metro.class);
		System.out.println(Metro.class.hashCode());
		
        System.out.println(context.getBean(Numbers.class).hashCode());
		
		Integer integer1=context.getBean("one", Integer.class);
		System.out.println(integer1.hashCode());
		
		System.out.println(context.getBean("two",Integer.class).hashCode());
		System.out.println(context.getBean("twentyOne",Integer.class).hashCode());
		System.out.println(context.getBean("thirtyThree",Integer.class).hashCode());
		System.out.println(context.getBean("fourtySix",Integer.class).hashCode());
		System.out.println(context.getBean("fiftyFive",Integer.class).hashCode());
		System.out.println(context.getBean("sixtyTwo",Integer.class).hashCode());
		System.out.println(context.getBean("twentySeven",Integer.class).hashCode());
		System.out.println(context.getBean("sixteen",Integer.class).hashCode());
		System.out.println(context.getBean("twoHundred",Integer.class).hashCode());
		System.out.println(context.getBean("nineteen",Integer.class).hashCode());
		System.out.println(context.getBean("sixty",Integer.class).hashCode());
		System.out.println(context.getBean("fifty",Integer.class).hashCode());
		System.out.println(context.getBean("fourty",Integer.class).hashCode());
		System.out.println(context.getBean("twoHundredTwenty",Integer.class).hashCode());
		System.out.println(context.getBean("seven",Integer.class).hashCode());	
        System.out.println(context.getBean(Colors.class).hashCode());
		
		System.out.println(context.getBean(Animals.class).hashCode());
		
		System.out.println(context.getBean(Numbers.class).hashCode());
	}

}
